/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IGelato, IGelatoInterface } from "../IGelato";

const _abi = [
  {
    inputs: [],
    name: "getFeeCollector",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGelato__factory {
  static readonly abi = _abi;
  static createInterface(): IGelatoInterface {
    return new utils.Interface(_abi) as IGelatoInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGelato {
    return new Contract(address, _abi, signerOrProvider) as IGelato;
  }
}
