/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { GuniResolver, GuniResolverInterface } from "../GuniResolver";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IGUniPool",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0In",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1In",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price18Decimals",
        type: "uint256",
      },
    ],
    name: "getRebalanceParams",
    outputs: [
      {
        internalType: "bool",
        name: "zeroForOne",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "swapAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class GuniResolver__factory {
  static readonly abi = _abi;
  static createInterface(): GuniResolverInterface {
    return new utils.Interface(_abi) as GuniResolverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GuniResolver {
    return new Contract(address, _abi, signerOrProvider) as GuniResolver;
  }
}
